export const UPDATE_PRICE_SORT = 'UPDATE_PRICE_SORT';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const FAILED_TO_UPDATE_PRODUCTS = 'FAILED_TO_UPDATE_PRODUCTS';
export const UPDATE_COUNT = 'UPDATE_COUNT';
export const UPDATE_QUERY_PARAMS = 'UPDATE_QUERY_PARAMS';
export const UPDATE_LIMIT = 'UPDATE_LIMIT';
export const UPDATE_OFFSET = 'UPDATE_OFFSET';